WIP Instruction for mill installation on Windows
lsug/lsug-website pull request #67
Opened 2020-11-28 18:05 UTC by mazhara

draft commit

2020-12-12 15:20 UTC, zainab-ali requested changes

2020-12-12 15:20 UTC, zainab-ali commented on CONTRIBUTING.md
> +####Windows
There needs to be a space after the # sign here

2020-12-14 21:05 UTC, zainab-ali requested changes
Thanks Olga!
This is a great start.  I've a few suggestions.
While writing the comments, I pushed a few changes to a branch.  Have a look at it for inspiration:
https://github.com/mazhara/lsug-website/compare/windows_inst...zainab-ali:windows_inst

2021-01-02 01:45 UTC, mazhara commented on CONTRIBUTING.md
> +`mill server.test --no-service`
I have rechecked. mill.bat works. Only difference , for windows command line we can use just 'mill' while for windows PowerShell  './mill'. I have added it 'Checking your setup' remark

2021-01-06 19:59 UTC, zainab-ali commented on CONTRIBUTING.md
> +`mill server.test --no-service`
Thanks!

2021-01-06 19:59 UTC, zainab-ali commented
Thanks @mazhara ! This is good to go

2021-01-06 19:59 UTC, merged